#
# 5x5 Engineering @ 5x5 Technologies, Inc.
#
# Created       : 2023-03-01
# Last Modified : 2023-03-01
#
# Description
#    This file summarizes the set of checks that pre-commit will perform
#    prior to any commit.

default_stages: [commit, manual]

# Repositories to use
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml # Checks yaml files for parseable syntax.
      - id: check-json # Checks json files for parseable syntax.
      - id: check-added-large-files
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      # - id: requirements-txt-fixer # Sorts entries in requirements.txt
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3.9

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
        exclude: hooks.py
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
